### ISSUE TITLE
[BUG] Recommended videos that pop up at the end of a video are unaffected by the Appear Chance setting

### ISSUE THREAD

**Issue by iCeParadox64** [MagicJinn/Youtube-DougDougify#1]
I have my Appear Chance set to 2% and that works fine everywhere *except* the recommended video endcards that pop up after a video finishes.

Look at the videos on the sidebar, versus the same videos in the video player:    
![image](https://github.com/MagicJinn/Youtube-DougDougify/assets/25655781/9301ac81-3225-4759-8655-950bbf786bb6)

**Comment by MagicJinn** [comment]
Thanks for the report, should be a relatively easy fix

**Comment by MagicJinn** [comment]
Fixed in dev, uploading new version now. Coincidentally, the fix for this also allows multiple versions of this extension to be compatible with eachother, very cool!
